import { StyleSheet } from "react-native";

export default StyleSheet.create({
  // Top section with gauges and engine controls
  topSection: {
    paddingTop: 10,
    paddingHorizontal: 20,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#333',
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#444',
  },
  gaugeContainer: {
    flexDirection: 'row',
    gap: 20,
    flex: 1,
  },
  displayBox: {
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    padding: 15,
    borderRadius: 10,
    minWidth: 140,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#555',
  },
  displayText: {
    fontSize: 28,
    fontWeight: 'bold',
    color: 'white',
    textAlign: 'center',
  },
  statusText: {
    color: 'white',
    fontSize: 14,
    fontWeight: 'bold',
    textAlign: 'center',
    marginTop: 10,
    flex: 1,
  },

  // Engine control button
  engineButton: {
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 20,
    marginLeft: 20,
    borderWidth: 2,
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 80,
  },
  engineOn: {
    backgroundColor: '#F44336',
    borderColor: '#D32F2F',
  },
  engineOff: {
    backgroundColor: '#4CAF50',
    borderColor: '#388E3C',
  },
  engineButtonText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 16,
  },

  // Main section with pedals and gear shifter
  mainSection: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingBottom: 30,
    alignItems: 'center',
    backgroundColor: '#222',
  },
  pedalsSection: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 30,
    marginRight: 20,
  },
  gearSection: {
    alignItems: 'center',
    marginLeft: 20,
  },

  // Pedal styles
  pedalContainer: {
    width: 70,
    height: 200,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  pedalLabel: {
    color: 'white',
    fontSize: 18,
    marginBottom: 10,
    fontWeight: 'bold',
  },
  pedalTrack: {
    width: 50,
    height: 160,
    backgroundColor: '#111',
    borderRadius: 25,
    position: 'relative',
    borderWidth: 3,
    borderColor: '#333',
    overflow: 'hidden',
  },
  pedalThumb: {
    width: 50,
    height: 50,
    borderRadius: 25,
    position: 'absolute',
    left: 0,
    borderWidth: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 3,
    elevation: 5,
  },

  // Gear shifter styles
  gearbox: {
    width: 220,
    height: 180,
    borderWidth: 3,
    borderColor: '#444',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#1a1a1a',
    borderRadius: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 5,
    elevation: 8,
  },
  gearRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    gap: 15,
  },
  gearRowCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginVertical: 5,
  },
  gearButton: {
    width: 50,
    height: 40,
    backgroundColor: '#2a2a2a',
    borderRadius: 8,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#3a3a3a',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 2,
    elevation: 3,
  },
  gearButtonActive: {
    backgroundColor: '#4a4a4a',
    borderColor: '#5a5a5a',
    shadowColor: '#fff',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  gearButtonDisabled: {
    backgroundColor: '#1a1a1a',
    borderColor: '#2a2a2a',
  },
  gearText: {
    color: '#eee',
    fontWeight: 'bold',
    fontSize: 18,
    textShadowColor: 'rgba(0,0,0,0.5)',
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  gearTextDisabled: {
    color: '#444',
    textShadowColor: 'transparent',
  },
});